export const carNames: Array<string> = [
    'Audi',
    'Alfa Romeo',
    'Kolymaga',
    'Aston Martin',
    'Razvalyha',
    'Ford',
    'Ferrari',
    'Fiat',
    'GAZ',
    'GMC',
    'Honda',
    'Hummer',
    'Hyundai',
    'Infiniti',
    'Isuzu',
    'Vedro-z-Boltamy',
    'Jaguar',
    'Jeep',
    'Kamaz',
    'Lada',
    'Lexus',
    'Lotus',
    'MAN',
    'Maybach',
    'MAZ',
    'Mazda',
    'McLaren',
    'Nissan',
    'Opel',
    'Drandulet',
    'Konserwnaya-Banka',
    'Pontiac',
    'Porsche',
    'Renault',
    'Škoda',
    'Bibika',
    'Subaru',
    'Suzuki',
    'Tesla',
    'Toyota',
    'UAZ',
    'Volvo',
    'ZAZ',
    'Koryto',
    'TVR',
    'Saab',
    'RAM',
    'Chevrolet',
    'Traktor',
    'Daewoo',
  ];
  